[package]
name = "rust_os"
version = "0.1.0"
edition = "2018"
authors = ["Evan Anderson <evan.w.and@gmail.com>"]

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
